# First draft of config file.
# TODO: This is very user unfriendly.
# Make sure parameters are listed in a sensible
# order and fully explained with comments.
Schemes:
    Posterior:
        Colour: 'RoyalBlue'
        Symbol: '-'
        Label: 'Posterior pdf'
        ColourMap: 'GnBu'
        Colours: ['RoyalBlue', 'SeaGreen']
        ColourBarTitle: 'PDF'
        LevelNames: ['$2\sigma$ region', '$1\sigma$ region']
    PosteriorMean:
        Colour: 'SeaGreen'
        Symbol: 'o'
        Label: 'Posterior Mean'
    BestFit:
        Colour: 'Brown'
        Symbol: '*'
        Label: 'Best-fit point'
        Size: 12
    ProfLike:
        Colour: 'DarkOrange'
        Symbol: '--'
        Label: 'Profile likelihood'
        ColourMap: 'Reds'
        Colours: ['DarkOrange', 'Brown']
        ColourBarTitle: 'PL'
        LevelNames: ['$2\sigma$ region', '$1\sigma$ region']
    ProfChiSq:
        Colour: 'DarkOrange'
        Symbol: '--'
        Label: '$\Delta \chi^2$'
        Colours: ['Gold', 'Peru']
        LevelNames: ['$2\sigma$ excluded', '$1\sigma$ excluded']
    Scatter:
        Symbol: 'o'
        ColourMap: 'Reds'
        Size: 15
    ConfIntervalS2:
        Colour: 'DarkOrange'
        Symbol: 'o'
        Label: '$2\sigma$ confidence interval'
    ConfIntervalS1:
        Colour: 'Brown'
        Symbol: 'o'
        Label: '$1\sigma$ confidence interval'
    CredibleRegionS2:
        Colour: 'SeaGreen'
        Symbol: '-'
        Label: '$2\sigma$ credible region'
    CredibleRegionS1:
        Colour: 'RoyalBlue'
        Symbol: '-'
        Label: '$1\sigma$ credible region'
    TauBand:
        Colour: 'RoyalBlue'
        Label: 'Theory Error'
        
#########################################################################
PlotOptions:
    # Technical plot options.       
    dof: 10
    alpha: [0.05, 0.32] # Values of alpha, in ascending order.
    # AF This should be called alpha, and what breaks if not ascending?
    # plot_limits: [0,0.2,0,1.3]
    plot_limits: null 
    # bin_limits: [[0,1000],[0,1000]]
    bin_limits: null
    nbins: 70

    # Plot appearance.
    xticks: 5 # Numbers of ticks.
    yticks: 5
    
    plottitle: 'Fowlie (2014)'

    # Size in inches.
    size: [8, 8]

    # For theoretical error on delta chi-squared plots.
    Tau: 2
    
    # Whether to use LaTeX.
    # - all: use LaTeX for math and text
    # - math: use LaTeX for math only
    # - none: do not use LaTeX at all
    usetex: 'all'



















